// Export all entities
export * from './User';
export * from './Department';
export * from './Patient';
export * from './Appointment';
export * from './Billing';
export * from './Medicine';
export * from './LabTest';
export * from './Ward';
export * from './Employee';
export * from './Radiology';
export * from './Analytics';
export * from './Doctor';
